import type { User, Event } from './types';

export const users: User[] = [
  {
    id: '1',
    name: 'University Admin',
    email: 'admin@uni.edu',
    role: 'admin',
  },
  {
    id: '2',
    name: 'CS Dept Head',
    email: 'cs@uni.edu',
    role: 'organizer',
  },
  {
    id: '3',
    name: 'Alice Smith',
    email: 'alice@uni.edu',
    role: 'student',
  },
  {
    id: '4',
    name: 'Bob Johnson',
    email: 'bob@uni.edu',
    role: 'student',
  },
  {
    id: '5',
    name: 'Arts Dept Coordinator',
    email: 'arts@uni.edu',
    role: 'organizer',
  },
];

export const events: Event[] = [
  {
    id: '1',
    name: 'Annual Hackathon 2024',
    description: 'A 24-hour coding challenge for all engineering departments. Build innovative solutions and win certificates.',
    date: '2024-10-26',
    time: '9:00 AM - 9:00 AM (Next Day)',
    location: 'Main Engineering Block, Hall A',
    organizerId: '2',
    department: 'Computer Science',
    category: 'Tech',
  },
  {
    id: '2',
    name: 'Inter-Uni Debate Championship',
    description: 'The premier debating event where universities compete on global policy issues.',
    date: '2024-11-15',
    time: '10:00 AM - 4:00 PM',
    location: 'Central Auditorium',
    organizerId: '5',
    department: 'Social Sciences',
    category: 'Debate',
  },
  {
    id: '3',
    name: 'Robotics Workshop',
    description: 'Learn to build and program your first robot. Parts and guidance provided by the robotics lab.',
    date: '2024-11-05',
    time: '1:00 PM - 5:00 PM',
    location: 'Lab 402, Science Building',
    organizerId: '2',
    department: 'Computer Science',
    category: 'Workshop',
  },
  {
    id: '4',
    name: 'Departmental Freshers Welcome',
    description: 'Welcoming the new batch of students with cultural performances and networking.',
    date: '2024-09-22',
    time: '4:00 PM - 8:00 PM',
    location: 'Open Garden Area',
    organizerId: '5',
    department: 'Arts & Humanities',
    category: 'Social',
  },
  {
    id: '5',
    name: 'University Sports Meet',
    description: 'The annual athletics and team sports competition between various campus departments.',
    date: '2024-10-12',
    time: '8:00 AM - 6:00 PM',
    location: 'University Sports Ground',
    organizerId: '2',
    department: 'Physical Education',
    category: 'Sports',
  },
];
