import type { User, Event } from './types';
import { PlaceHolderImages } from './placeholder-images';

export const placeHolderImages = PlaceHolderImages;

export const users: User[] = [
  {
    id: '1',
    name: 'Admin User',
    email: 'admin@eventverse.com',
    role: 'admin',
    avatar: placeHolderImages.find(img => img.id === 'user-avatar-1')?.imageUrl || '',
  },
  {
    id: '2',
    name: 'Manager User',
    email: 'manager@eventverse.com',
    role: 'manager',
    avatar: placeHolderImages.find(img => img.id === 'user-avatar-2')?.imageUrl || '',
  },
  {
    id: '3',
    name: 'Regular User',
    email: 'user@eventverse.com',
    role: 'user',
    avatar: placeHolderImages.find(img => img.id === 'user-avatar-3')?.imageUrl || '',
  },
  {
    id: '4',
    name: 'Jane Doe',
    email: 'jane.doe@example.com',
    role: 'user',
    avatar: placeHolderImages.find(img => img.id === 'user-avatar-4')?.imageUrl || '',
  },
  {
    id: '5',
    name: 'John Smith',
    email: 'john.smith@example.com',
    role: 'manager',
    avatar: placeHolderImages.find(img => img.id === 'user-avatar-1')?.imageUrl || '',
  },
];

export const events: Event[] = [
  {
    id: '1',
    name: 'Starlight Music Festival',
    description: 'An unforgettable night under the stars with the world\'s top DJs and live bands. Experience music like never before.',
    date: '2024-10-26',
    time: '6:00 PM - 2:00 AM',
    location: 'Emerald Valley Park',
    image: placeHolderImages.find(img => img.id === 'event-concert')?.imageUrl || '',
    price: 75.00,
    managerId: '2',
    category: 'Music',
  },
  {
    id: '2',
    name: 'Future of AI Conference',
    description: 'Join industry leaders and innovators to explore the cutting edge of Artificial Intelligence and its impact on our world.',
    date: '2024-11-15',
    time: '9:00 AM - 5:00 PM',
    location: 'Grand Tech Convention Center',
    image: placeHolderImages.find(img => img.id === 'event-conference')?.imageUrl || '',
    price: 250.00,
    managerId: '5',
    category: 'Tech',
  },
  {
    id: '3',
    name: 'Creative Coding Workshop',
    description: 'A hands-on workshop for artists and developers looking to blend code and creativity. No prior experience needed.',
    date: '2024-11-05',
    time: '10:00 AM - 4:00 PM',
    location: 'City Art & Innovation Hub',
    image: placeHolderImages.find(img => img.id === 'event-workshop')?.imageUrl || '',
    price: 50.00,
    managerId: '2',
    category: 'Workshop',
  },
  {
    id: '4',
    name: 'Annual Community Picnic',
    description: 'A fun day out for the whole family with games, food trucks, and live entertainment. A perfect community get-together.',
    date: '2024-09-22',
    time: '12:00 PM - 6:00 PM',
    location: 'Sunny Meadows',
    image: placeHolderImages.find(img => img.id === 'event-community')?.imageUrl || '',
    price: 0.00,
    managerId: '5',
    category: 'Community',
  },
  {
    id: '5',
    name: 'Championship Soccer Finals',
    description: 'Witness the thrilling conclusion of the season as the top two teams battle for the championship trophy.',
    date: '2024-10-12',
    time: '7:30 PM',
    location: 'Victory Stadium',
    image: placeHolderImages.find(img => img.id === 'event-sports')?.imageUrl || '',
    price: 45.00,
    managerId: '2',
    category: 'Sports',
  },
  {
    id: '6',
    name: 'Digital Marketing Webinar',
    description: 'Learn the latest trends and strategies in digital marketing from the comfort of your home. Free for all attendees.',
    date: '2024-09-30',
    time: '2:00 PM - 3:30 PM',
    location: 'Online',
    image: placeHolderImages.find(img => img.id === 'event-webinar')?.imageUrl || '',
    price: 0.00,
    managerId: '5',
    category: 'Webinar',
  },
];
